ecommerceshop/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', include('shop.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:product_id>', views.detail, name='detail'),
    path('basket', views.basket, name='basket'),
    path('basket/add/<int:product_id>', views.add_to_basket, name='add-to-basket'),
    path('basket/update/<int:product_id>', views.update_basket, name='update-basket'),
    path('basket/buy', views.buy_basket, name='buy-basket'),
    path('basket/clear', views.clear_basket, name='clear-basket')
]

shop/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='products')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Transaction(models.Model):
    # transaction_number = models.IntegerField()
    order_date = models.DateTimeField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return 'Transaction_%s' % self.pk


class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(default=0)
    transaction = models.ForeignKey(Transaction, on_delete=models.PROTECT)

    def __str__(self):
        return '%s %s' % (self.transaction, self.product)

shop/views.py
from django.http import HttpResponseRedirect, HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
import requests, json
from .utils import PAYMENT_CONFIG

from .models import Product, Order, Transaction
import logging

logger = logging.getLogger(__name__)


def index(request):
    # del request.session['basket']
    # del request.session['basket_size']
    products_list = Product.objects.filter(active=True)
    return render(request, 'shop/index.html', {'products_list': products_list})


def detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'shop/detail.html', {'product': product})


def basket(request):
    products = []
    total_price = 0
    if 'basket' in request.session:
        for bs in request.session['basket']:
            p = get_object_or_404(Product, pk=int(bs['item']))
            p.basket = int(bs['amount'])
            p.price_sum = p.basket * p.price
            total_price += p.price_sum
            products.append(p)
    return render(request, 'shop/basket.html', {'products': products, 'total_price': total_price})


def add_to_basket(request, product_id):
    product = get_object_or_404(Product, pk=product_id)

    try:
        if 'basket' not in request.session:
            request.session['basket'] = []
        if 'basket_size' not in request.session:
            request.session['basket_size'] = 0

        in_basket = False
        size = request.POST['basket-quantity']

        for bs in request.session['basket']:
            if int(bs['item']) == product_id:
                if int(size) + int(bs['amount']) > product.quantity:
                    size = product.quantity - int(bs['amount'])
                bs['amount'] = int(size) + int(bs['amount'])
                request.session['basket_size'] = int(size) + int(request.session['basket_size'])
                in_basket = True

        if not in_basket:
            request.session['basket'].append({'item': product_id, 'amount': size})
            request.session['basket_size'] = int(size) + int(request.session['basket_size'])

        request.session.modified = True
    except KeyError:
        return HttpResponseRedirect(reverse('shop:detail', args=(product_id,)))
    else:
        return HttpResponseRedirect('/')


def update_basket(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    size = request.POST['basket-update']
    for bs in request.session['basket']:
        if int(bs['item']) == product_id:
            if int(size) > product.quantity:
                size = product.quantity
            elif int(size) < 0:
                size = 0
            size_diff = int(size) - int(bs['amount'])
            bs['amount'] = int(size)

            if int(size) == 0:
                request.session['basket'].remove(bs)

            request.session['basket_size'] = int(size_diff) + int(request.session['basket_size'])
            request.session.modified = True

    return HttpResponseRedirect(reverse('shop:basket'))


def buy_basket(request):
    products = []
    price_total = 0
    for bs in request.session['basket']:
        product = get_object_or_404(Product, pk=int(bs['item']))
        size = int(bs['amount'])
        price = size * product.price
        price_total += price
        products.append({
            'name': product.name,
            'unitPrice': str(int(product.price * 100)),
            'quantity': str(int(size))
        })
    price_total = int(price_total * 100)

    header = {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer 3e5cac39-7e38-4139-8fd6-30adc06a61bd'
    }
    body = {
        "notifyUrl": "https://ecommerceshop.free.beeceptor.com/notify",
        "customerIp": "127.0.0.1",
        "merchantPosId": "145227",
        "description": "Przykladowe zamowienie na potrzeby projektu",
        "currencyCode": "PLN",
        "totalAmount": str(price_total),
        "buyer": {
            "email": "szymon.liszka@example.com",
            "phone": "123123123",
            "firstName": "Szymon",
            "lastName": "Liszka",
            "language": "pl"
        },
        "settings": {
            "invoiceDisabled": "true"
        },
        "products": products
    }
    r = requests.post('https://secure.payu.com/api/v2_1/orders', headers=header, json=body)

    if str(r.status_code).startswith('2'):
        save_transaction(request)
        return render(request, 'shop/buy.html', {'redirect_url': r.url})
    else:
        return render(request, 'shop/error.html')

    # nie dziala z powodu nie dzialajacej strony - prace konserwacyjne
    # r = requests.post('https://secure.snd.payu.com/pl/standard/user/oauth/authorize', params=PAYMENT_CONFIG['OAuth'])
    #
    # if str(r.status_code).startswith('2'):
    #     logger.info(r.request)
    #     logger.info(r.json())
    #     logger.info(r.json()['access_token'])
    #     logger.info(PAYMENT_CONFIG['loging'])
    #
    #     header = {
    #         "Content-Type": PAYMENT_CONFIG['Content-Type'],
    #         "Authorization": PAYMENT_CONFIG['Authorization'] + ' ' + r.json()['access_token']
    #     }
    #     body = {
    #         "notifyUrl": PAYMENT_CONFIG['notifyUrl'],
    #         "customerIp": PAYMENT_CONFIG['customerIp'],
    #         "merchantPosId": PAYMENT_CONFIG['merchantPosId'],
    #         "description": "Zakupy za pomoca przykladowego sklepu PayU",
    #         "currencyCode": PAYMENT_CONFIG['currencyCode'],
    #         "totalAmount": str(price_total),
    #         "settings": PAYMENT_CONFIG['settings'],
    #         "products": products
    #     }
    #
    #     r = requests.post('https://secure.snd.payu.com/api/v2_1/orders', headers=header, json=body)
    #
    #     save_transaction(request)
    #
    #     return render(request, 'shop/buy.html', {'redirect_url': r.url})
    # else:
    #     return render(request, 'shop/error.html')


def clear_basket(request):
    if 'basket' in request.session:
        request.session['basket'] = []
    if 'basket_size' in request.session:
        request.session['basket_size'] = 0
    return HttpResponseRedirect(reverse('shop:basket'))


def save_transaction(req):
    transaction = Transaction(order_date=timezone.now(), price=0)
    transaction.save()

    price_total = 0
    for bs in req.session['basket']:
        product = get_object_or_404(Product, pk=int(bs['item']))
        size = int(bs['amount'])
        price = size * product.price
        price_total += price

        product.quantity -= size
        product.save()

        o = Order(product=product, quantity=size, transaction=transaction)
        o.save()

    transaction.price = price_total
    transaction.save()

    if 'basket' in req.session:
        req.session['basket'] = []
    if 'basket_size' in req.session:
        req.session['basket_size'] = 0

shop/templates/shop/basket.html
<!DOCTYPE html>
    {% load static %}
    <head>
        <meta charset="utf-8">
        <title>Sklep</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'shop/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'shop/bootstrap.min.css' %}">
    </head>
    <body>
        {% include "shop/navbar.html" %}
        <div class="container">
            <div class="row justify-content-center mb-4">
                <div class="col-lg-8 col-md-11 shop-background">
                    <div class="p-2 my-4 text-center text-white bg-primary rounded">
                        <h1>Przedmioty w koszyku:</h1>
                    </div>
                    {% if products %}
                        {% for product in products %}
                            <div class="media p-3 my-3 border border-primary rounded">
                                <img class="mr-5 align-self-center very-small-image" src="{{ product.image.url }}" alt="Zdjecie produktu"/>
                                <div class="media-body">
                                    <div class="mb-1 font-weight-bold">{{ product.name }}</div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div>Cena za sztukę: {{ product.price }} zł</div>
                                            <div>W koszyku: {{ product.basket }}</div>
                                            <div class="mt-2">Łączna cena {{ product.price_sum }} zł</div>
                                        </div>
                                        <div class="col-md-6 mt-md-0 mt-2">
                                            <form method="post" action="{% url 'shop:update-basket' product.id %}">
                                                {% csrf_token %}
                                                <div>Zmień zamówienie:</div>
                                                <div class="form-group row my-0">
                                                    <div class="col">
                                                        <input class="form-control form-control-sm" type="number" id="change" name="basket-update" value="{{ product.basket }}" min="0" max="{{ product.quantity }}" required>
                                                    </div>
                                                    <label class="col col-form-label" for="change">
                                                        z {{ product.quantity }}
                                                    </label>
                                                </div>
                                                <input class="btn btn-success btn-sm" type="submit" value="Zmień">
                                            </form>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        {% endfor %}
                            <div class="my-4 text-center">
                                <h4 class="font-weight-bold">Łączna cena zamówienia: {{ total_price }} zł</h4>
                            </div>
                            <form class="d-flex justify-content-around my-4">
                                {% csrf_token %}
                                <button class="btn btn-warning" type="submit" formmethod="post" formaction="{% url 'shop:clear-basket' %}">Wyczyść koszyk</button>
                                <button class="btn btn-success" type="submit" formmethod="post" formaction="{% url 'shop:buy-basket' %}">Wykonaj zamówienie</button>
                            </form>
                    {% else %}
                        <h4 class="my-5 text-center">Nie masz żadnych przedmiotów w koszyku</h4>
                    {% endif %}
                </div>
            </div>
        </div>
    <script type="text/javascript" src="{% static 'shop/jquery-3.5.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'shop/bootstrap.min.js' %}"></script>
    </body>

</html>

shop/templates/shop/buy.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sklep</title>
    <style>
        #redlink {display: none}
    </style>
    <link rel="stylesheet" type="text/css" href="{% static 'shop/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'shop/bootstrap.min.css' %}">
</head>
<body>
    <a id="redlink" target="_blank" href="{{ redirect_url }}">Przeniesienie do platnosci</a>
    {% include "shop/navbar.html" %}
    <div class="container">
        <div class="row justify-content-center mb-4">
            <div class="col-lg-8 col-md-11 shop-background">
                <div class="p-2 my-4 text-center text-white bg-success rounded">
                    <h2>Dziękujemy za zakupy w naszym sklepie.</h2>
                </div>
                <div class="my-4 text-center">
                    <a class="a-link" href="{% url 'shop:index' %}">Powrót do strony głównej</a>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'shop/bootstrap.min.js' %}"></script>
</body>
<script type="application/javascript">
    document.getElementById("redlink").click();
</script>
</html>

shop/templates/shop/detail.html
<!DOCTYPE html>
    {% load static %}
    <head>
        <meta charset="utf-8">
        <title>Sklep</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'shop/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'shop/bootstrap.min.css' %}">
    </head>
    <body>
        {% include "shop/navbar.html" %}
        <div class="container">
            <div class="row justify-content-center mb-4">
                <div class="col-lg-8 col-md-11 shop-background">
                    <div class="media p-3 my-3">
                        <img class="mr-5 big-image" src="{{ product.image.url }}" alt="Zdjecie produktu"/>
                        <div class="media-body">
                            <h3 class="mb-3 font-weight-bold">{{ product.name }}</h3>
                            <div><strong>Opis:</strong><br>{{ product.description }}</div>
                            <div><strong>Cena:</strong> {{ product.price }} zł</div>
                            <div><strong>Zostało sztuk:</strong> {{ product.quantity }}</div>
                        </div>
                    </div>
                    <form method="post" action="{% url 'shop:add-to-basket' product.id %}">
                        {% csrf_token %}
                        <div class="form-group col-sm-5">
                            <label class="col-form-label" for="Quantity">Ile sztuk chcesz kupić: </label>
                            <input class="form-control" type="number" id="Quantity" name="basket-quantity" min="0" max="{{ product.quantity }}" required>
                            <input class="btn btn-success my-2" type="submit" value="Do koszyka">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </body>
    <script type="text/javascript" src="{% static 'shop/jquery-3.5.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'shop/bootstrap.min.js' %}"></script>
</html>

shop/templates/shop/error.html
<!DOCTYPE html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Sklep</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'shop/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'shop/bootstrap.min.css' %}">
</head>
<body>
    {% include "shop/navbar.html" %}
    <div class="container">
        <div class="row justify-content-center mb-4">
            <div class="col-lg-8 col-md-11 shop-background">
                <div class="p-2 my-4 text-center text-white bg-danger rounded">
                    <h2>Przepraszamy nastąpił błąd podczas przetwarzania.</h2>
                </div>
                <div class="my-4 text-center">
                    <a class="a-link" href="{% url 'shop:index' %}">Powrót do strony głównej</a>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'shop/bootstrap.min.js' %}"></script>
</body>
</html>

shop/templates/shop/index.html
<!DOCTYPE html>
    {% load static %}
    <head>
        <meta charset="utf-8">
        <title>Sklep</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'shop/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'shop/bootstrap.min.css' %}">
    </head>
    <body>
        {% include "shop/navbar.html" %}
        <div class="container">
            <div class="row justify-content-center mb-4">
                <div class="col-lg-8 col-md-11 shop-background">
                    <div class="p-2 my-4 text-center text-white bg-primary rounded">
                        <h1>Lista produktów:</h1>
                    </div>
                    {% if products_list %}
                        {% for product in products_list %}
                        <a class="a-link" href="{% url 'shop:detail' product.id %}">
                            <div class="media p-3 my-3 border border-primary rounded btn-outline-secondary">
                                <img class="mr-5 small-image" src="{{ product.image.url }}" alt="Zdjecie produktu"/>
                                <div class="media-body">
                                    <h5 class="mb-3 font-weight-bold">{{ product.name }}</h5>
                                    <div>Cena: {{ product.price }} zł</div>
                                    <div>Zostało sztuk: {{ product.quantity }}</div>
                                </div>
                            </div>
                        </a>
                        {% endfor %}
                    {% else %}
                        <div class="p-3 my-4 text-center text-white bg-danger rounded">
                            <h4>W tej chwili nie ma żadnych produktów do kupienia</h4>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </body>
    <script type="application/javascript" src="{% static 'shop/jquery-3.5.1.min.js' %}"></script>
    <script type="application/javascript" src="{% static 'shop/bootstrap.min.js' %}"></script>
</html>

shop/templates/shop/navbar.html
<nav class="navbar navbar-expand justify-content-between navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'shop:index' %}">Sklep</a>
    <a class="navbar-brand" href="{% url 'shop:basket' %}">
        Koszyk {% if request.session.basket_size %} <span class="badge badge-light">{{request.session.basket_size}}</span>{% endif %}
    </a>
</nav>